//Authentication Reducer Actions
export const START_AUTHENTICATION_LOADING = 'START_AUTHENTICATION_LOADING';
export const STOP_AUTHENTICATION_LOADING = 'STOP_AUTHENTICATION_LOADING';
export const START_LOG_OUT_LOADING = 'START_LOG_OUT_LOADING';
export const STOP_LOG_OUT_LOADING = 'STOP_LOG_OUT_LOADING';
export const STORE_USER_DETAILS = 'STORE_USER_DETAILS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const UPDATE_LOGIN_EMAIL = 'UPDATE_LOGIN_EMAIL';

//Income Expense Reducer Actions
export const START_INCOME_EXPENSE_LOADING = 'START_INCOME_EXPENSE_LOADING';
export const STOP_INCOME_EXPENSE_LOADING = 'STOP_INCOME_EXPENSE_LOADING';
export const START_ADD_INCOME_EXPENSE_LOADING = 'START_ADD_INCOME_EXPENSE_LOADING';
export const STOP_ADD_INCOME_EXPENSE_LOADING = 'STOP_ADD_INCOME_EXPENSE_LOADING';
export const STORE_INCOME_EXPENSE_DETAILS = 'STORE_INCOME_EXPENSE_DETAILS';
export const CLEAR_INCOME_EXPENSE_DETAILS = 'CLEAR_INCOME_EXPENSE_DETAILS';


export const START_INCOME_EXPENSE_REPORT_LOADING = 'START_INCOME_EXPENSE_REPORT_LOADING';
export const STOP_INCOME_EXPENSE_REPORT_LOADING = 'STOP_INCOME_EXPENSE_REPORT_LOADING';
export const STORE_INCOME_EXPENSE_REPORT_DATA = 'STORE_INCOME_EXPENSE_REPORT_DATA';
export const CLEAR_INCOME_EXPENSE_REPORT_DATA = 'CLEAR_INCOME_EXPENSE_REPORT_DATA';